FurnitureHouse/Controllers/BrandsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FurnitureHouse.Data;
using FurnitureHouse.Models;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace FurnitureHouse.Controllers
{
    [Authorize(Roles = "power")]
    public class BrandsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _environment;

        public BrandsController(ApplicationDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _environment = env;
        }

        // GET: Brands
        public async Task<IActionResult> Index()
        {
            return View(await _context.Brands.ToListAsync());
        }

       // GET: Brands/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Brands/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BrandID,BrandName,Traits,Material,File")] Brand brand)
        {
            using (var memoryStream = new MemoryStream())
            {
                await brand.File.FormFile.CopyToAsync(memoryStream);

                string photoname = brand.File.FormFile.FileName;
                brand.Extension = Path.GetExtension(photoname);
                if (!".jpg.jpeg.png.gif.bmp".Contains(brand.Extension.ToLower()))
                {
                    ModelState.AddModelError("File.FormFile", "Only Images Allowed");
                }
                else
                {
                    ModelState.Remove("Extension");
                }
            }
            if (ModelState.IsValid)
            {
                _context.Add(brand);
                await _context.SaveChangesAsync();
                var uploadsRootFolder = Path.Combine(_environment.WebRootPath, "brands");
                if (!Directory.Exists(uploadsRootFolder))
                {
                    Directory.CreateDirectory(uploadsRootFolder);
                }
                string filename = brand.BrandID + brand.Extension;
                var filePath = Path.Combine(uploadsRootFolder, filename);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await brand.File.FormFile.CopyToAsync(fileStream).ConfigureAwait(false);
                }
                return RedirectToAction(nameof(Index));
            }
            return View(brand);
        }

        // GET: Brands/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands.FindAsync(id);
            if (brand == null)
            {
                return NotFound();
            }
            return View(brand);
        }

        // POST: Brands/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BrandID,BrandName,Traits,Material,Extension")] Brand brand)
        {
            if (id != brand.BrandID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(brand);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BrandExists(brand.BrandID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(brand);
        }

        // GET: Brands/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands
                .FirstOrDefaultAsync(m => m.BrandID == id);
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }

        // POST: Brands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var brand = await _context.Brands.FindAsync(id);
            _context.Brands.Remove(brand);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BrandExists(int id)
        {
            return _context.Brands.Any(e => e.BrandID == id);
        }
    }
}

FurnitureHouse/Controllers/FurnitureCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FurnitureHouse.Data;
using FurnitureHouse.Models;

namespace FurnitureHouse.Controllers
{
    public class FurnitureCategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FurnitureCategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: FurnitureCategories
        public async Task<IActionResult> Index()
        {
            return View(await _context.FurnitureCategories.ToListAsync());
        }

        

        // GET: FurnitureCategories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: FurnitureCategories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FurnitureCategoryID,FurnitureCategoryName")] FurnitureCategory furnitureCategory)
        {
            if (ModelState.IsValid)
            {
                _context.Add(furnitureCategory);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(furnitureCategory);
        }

        // GET: FurnitureCategories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var furnitureCategory = await _context.FurnitureCategories.FindAsync(id);
            if (furnitureCategory == null)
            {
                return NotFound();
            }
            return View(furnitureCategory);
        }

        // POST: FurnitureCategories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FurnitureCategoryID,FurnitureCategoryName")] FurnitureCategory furnitureCategory)
        {
            if (id != furnitureCategory.FurnitureCategoryID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(furnitureCategory);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FurnitureCategoryExists(furnitureCategory.FurnitureCategoryID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(furnitureCategory);
        }

        // GET: FurnitureCategories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var furnitureCategory = await _context.FurnitureCategories
                .FirstOrDefaultAsync(m => m.FurnitureCategoryID == id);
            if (furnitureCategory == null)
            {
                return NotFound();
            }

            return View(furnitureCategory);
        }

        // POST: FurnitureCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var furnitureCategory = await _context.FurnitureCategories.FindAsync(id);
            _context.FurnitureCategories.Remove(furnitureCategory);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FurnitureCategoryExists(int id)
        {
            return _context.FurnitureCategories.Any(e => e.FurnitureCategoryID == id);
        }
    }
}

FurnitureHouse/Controllers/FurnitureInfoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FurnitureHouse.Data;
using FurnitureHouse.Models;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace FurnitureHouse.Controllers
{
    [Authorize(Roles = "power")]
    public class FurnitureInfoesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _environment;

        public FurnitureInfoesController(ApplicationDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _environment = env;
        }

        // GET: FurnitureInfoes
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.FurnitureInfos.Include(f => f.Brand).Include(f => f.FurnitureSubCategory);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: FurnitureInfoes/Create
        public IActionResult Create()
        {
            ViewData["BrandID"] = new SelectList(_context.Brands, "BrandID", "BrandName");
            ViewData["FurnitureSubCategoryID"] = new SelectList(_context.FurnitureSubCategories, "FurnitureSubCategoryID", "FurnitureSubCategoryName");
            return View();
        }

        // POST: FurnitureInfoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FurnitureInfoID,FurnitureName,OfferPrice,Price,File,FurnitureSubCategoryID,BrandID")] FurnitureInfo furnitureInfo)
        {
            using (var memoryStream = new MemoryStream())
            {
                await furnitureInfo.File.FormFile.CopyToAsync(memoryStream);

                string photoname = furnitureInfo.File.FormFile.FileName;
                furnitureInfo.Extension = Path.GetExtension(photoname);
                if (!".jpg.jpeg.png.gif.bmp".Contains(furnitureInfo.Extension.ToLower()))
                {
                    ModelState.AddModelError("File.FormFile", "Only Images Allowed");
                }
                else
                {
                    ModelState.Remove("Extension");
                }
            }
            if (ModelState.IsValid)
            {
                _context.Add(furnitureInfo);
                await _context.SaveChangesAsync();
                var uploadsRootFolder = Path.Combine(_environment.WebRootPath, "furnitures");
                if (!Directory.Exists(uploadsRootFolder))
                {
                    Directory.CreateDirectory(uploadsRootFolder);
                }
                string filename = furnitureInfo.FurnitureInfoID + furnitureInfo.Extension;
                var filePath = Path.Combine(uploadsRootFolder, filename);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await furnitureInfo.File.FormFile.CopyToAsync(fileStream).ConfigureAwait(false);
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BrandID"] = new SelectList(_context.Brands, "BrandID", "BrandName", furnitureInfo.BrandID);
            ViewData["FurnitureSubCategoryID"] = new SelectList(_context.FurnitureSubCategories, "FurnitureSubCategoryID", "FurnitureSubCategoryName", furnitureInfo.FurnitureSubCategoryID);
            return View(furnitureInfo);
        }

        // GET: FurnitureInfoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var furnitureInfo = await _context.FurnitureInfos.FindAsync(id);
            if (furnitureInfo == null)
            {
                return NotFound();
            }
            ViewData["BrandID"] = new SelectList(_context.Brands, "BrandID", "BrandName", furnitureInfo.BrandID);
            ViewData["FurnitureSubCategoryID"] = new SelectList(_context.FurnitureSubCategories, "FurnitureSubCategoryID", "FurnitureSubCategoryName", furnitureInfo.FurnitureSubCategoryID);
            return View(furnitureInfo);
        }

        // POST: FurnitureInfoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FurnitureInfoID,FurnitureName,OfferPrice,Price,Extension,FurnitureSubCategoryID,BrandID")] FurnitureInfo furnitureInfo)
        {
            if (id != furnitureInfo.FurnitureInfoID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(furnitureInfo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FurnitureInfoExists(furnitureInfo.FurnitureInfoID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BrandID"] = new SelectList(_context.Brands, "BrandID", "BrandName", furnitureInfo.BrandID);
            ViewData["FurnitureSubCategoryID"] = new SelectList(_context.FurnitureSubCategories, "FurnitureSubCategoryID", "FurnitureSubCategoryName", furnitureInfo.FurnitureSubCategoryID);
            return View(furnitureInfo);
        }

        // GET: FurnitureInfoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var furnitureInfo = await _context.FurnitureInfos
                .Include(f => f.Brand)
                .Include(f => f.FurnitureSubCategory)
                .FirstOrDefaultAsync(m => m.FurnitureInfoID == id);
            if (furnitureInfo == null)
            {
                return NotFound();
            }

            return View(furnitureInfo);
        }

        // POST: FurnitureInfoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var furnitureInfo = await _context.FurnitureInfos.FindAsync(id);
            _context.FurnitureInfos.Remove(furnitureInfo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FurnitureInfoExists(int id)
        {
            return _context.FurnitureInfos.Any(e => e.FurnitureInfoID == id);
        }
    }
}

FurnitureHouse/ViewComponents/MenuViewComponent.cs
using FurnitureHouse.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FurnitureHouse.ViewComponents
{
    public class MenuViewComponent:ViewComponent
    {
		private readonly IMenuAccessService _menuAccessService;

		public MenuViewComponent(IMenuAccessService menuAccessService)
		{
			_menuAccessService = menuAccessService;
		}

		public async Task<IViewComponentResult> InvokeAsync()
		{
			var items = await _menuAccessService.GetMenu();

			return View(items);
		}
	}
}

FurnitureHouse/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Furniture House</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Anton&display=swap" rel="stylesheet">
    <style>
        .heading {
            font-family: 'Anton', sans-serif;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-white  heading" asp-area="" asp-controller="Home" asp-action="Index">Furniture House</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link  text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("power"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link text-white dropdown-toggle" href="#" id="drop1"
                                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Operations</a>
                                <div class="dropdown-menu" aria-labelledby="drop1">
                                    <a class="dropdown-item" asp-area="" asp-controller="Brands" asp-action="Index">Furniture Brands</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="FurnitureCategories" asp-action="Index">Furniture Categories</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="FurnitureSubCategories" asp-action="Index">Furniture Sub Categories</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="FurnitureInfoes" asp-action="Index">Furniture Info</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="Identity" asp-page="/Account/RegisterForPower">New Power User</a>
                            </li>
                        }
                        else
                        {
                            @await Component.InvokeAsync("Menu")


                            <li class="nav-item">
                                <a class="nav-link  text-white" asp-area="" asp-controller="Home" asp-action="AllBrands">Brands</a>
                            </li>
                            @if (SignInManager.IsSignedIn(User))
                            {
                                <li class="nav-item">
                                    <a class="nav-link  text-white" asp-area="" asp-controller="Home" asp-action="MyFavourites">Favourites</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link  text-white" asp-area="" asp-controller="Home" asp-action="ContactUs">Contact Us</a>
                            </li>

                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-white bg-dark">
        <div class="container">
            &copy; 2021 - Furniture House - <a class="text-white" asp-area="" asp-controller="Home" asp-action="ContactUs">Contact Us</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>